---
- name: install apache
  hosts: client2
  become: yes
   
  vars:
    source_file: ./index.html
    destin_file: /var/www/html

  tasks:
  - name: install apache
    apt: name=apache2


  - name: upload web site
    copy: src={{source_file}} dest={{destin_file}} mode=0644
    notify: restart apache

  - name: start apache
    service:
      name: apache2 
      state: started
      enabled: yes

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted 
