---
- name: install apache
  hosts: my_servers
  become: yes
   
  vars:
    source_file: ./index.html
    destin_file: /var/www/html

  tasks:
  - name: install apache
    apt: name=apache2
    when: ansible_os_family=="Debian"

  - name: install apache RED
    dnf: name=httpd
    when: ansible_os_family=="RED"


  - name: upload web site DEB
    copy: src={{source_file}} dest={{destin_file}} mode=0644
    when: ansible_os_family=="Debian"
    notify: restart debian

  - name: upload web site RED
    copy: src={{source_file}} dest={{destin_file}} mode=0644
    when: ansible_os_family=="RED"
    notify: restart red


  - name: start apache
    service:
      name: apache2 
      state: started
      enabled: yes
    when: ansible_os_family=="Debian"

  - name: start httpd
    service:
      name: httpd 
      state: started
      enabled: yes
    when: ansible_os_family=="Red"



  handlers:
  - name: restart debian
    service: name=apache2 state=restarted 
  handlers:
  - name: restart red
    service: name=httpd state=restarted 


