---
- name: install apache
  hosts: my_servers
  become: yes
   
  vars:
    source_folder: ./site
    destin_folder: /var/www/html

  tasks:
  - block: #debian
    - name: install apache
      apt: name=apache2


    - name: upload web site DEB
      copy: src={{ item }} dest={{ destin_folder }} mode=0644
      with_fileglob: "{{ source_folder }}/*"


    - name: start apache
      service:
        name: apache2 
        state: started
        enabled: yes
    when: ansible_os_family=="Debian"  

  - block: #red

    - name: install apache RED
      dnf: name=httpd
    
    - name: upload web site RED
      copy: 
        src: "{{ source_folder }}/{{ item }}" 
        dest: "{{ destin_folder }}"
        mode: 0644
      loop:
        - index.html
        - cat1.jpg
        - cat2.jpeg
      notify: restart red  


    - name: start httpd
      service:
        name: httpd 
        state: started
        enabled: yes

    when: ansible_os_family=="RED"

  handlers:
  - name: restart debian
    service: name=apache2 state=restarted 
  handlers:
  - name: restart red
    service: name=httpd state=restarted 
